### PR TITLE
Fixes for socket.io v1.3

### PR DESCRIPTION
**Pull request by areski**

### CODE REVIEW

**Comment by spromano** [comment]
@areski: thanks for the fix! Merging...

**Comment by areski** [comment]
Thanks to you, I'm really enjoying your book!

**Comment by spromano** [comment]
Thanks a lot! I’m working on the second edition, with tons of new (advanced) stuff…stay tuned ;-)

Simon

**Comment by areski** [comment]
As you mentioned there is a 2nd edition on the way, I have few comments on the book maybe that could help. Where can I reach you by email? my email contact is here https://github.com/areski

**Pull request merged**
